services:
  cms:
    container_name: cms
    image: cms
    build: .
    environment:
      DATABASE_URL: "host=cms_db user=postgres password=postgres dbname=cms sslmode=disable"
    ports:
      - "8000:8000"
    depends_on:
      - cms_db
  cms_db:
    container_name: cms_db
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: cms
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:  
  pgdata: {}



# services:
#   web:
#     build: .
#     env_file:
#       - app.env
#     ports:
#       - "8000:8000"
#     volumes:
#       - .:/cms
#     command: ./cms/main -b 0.0.0.0
#   db:
#     image: postgres:alpine
#     container_name: postgres
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=Mahesh@1119
#       - POSTGRES_DB=cms
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres-db:/var/lib/postgresql/data

# volumes:
#   postgres-db:




# # services:
# #   postgres:
# #     image: postgres
# #     container_name: postgres
# #     ports:
# #       - 6500:5432
# #     env_file:
# #       - ./app.env
# #     volumes:
# #       - postgres:/var/lib/postgresql/data
# # volumes:
# #   postgres: