// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/user/v1/accept": {
            "post": {
                "description": "This endpoint gives info of the acceptence the invitation.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Accept Invite."
                ],
                "summary": "Accept Invite.",
                "parameters": [
                    {
                        "description": "Accept Request Object",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AcceptRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.OutPutOfInvite"
                        }
                    }
                }
            }
        },
        "/user/v1/acceptslot/:user_id": {
            "post": {
                "description": "This endpoint gives info of the acceptence the invitation in the respective slots or time period which means if the slot is alraedy ocupied then he cannot join the other event but if the timmings is out of that event then event can be accepted.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Accept Invite in slot."
                ],
                "summary": "Accept Invite in slot Api.",
                "parameters": [
                    {
                        "description": "Accept Request Object",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/SlotAccept"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.OutPutOfInvite"
                        }
                    }
                }
            }
        },
        "/user/v1/event": {
            "post": {
                "description": "This endpoint allows you to create a event with event details .",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "create Invite Api."
                ],
                "summary": "create Event Api.",
                "parameters": [
                    {
                        "description": "Accept Request Object",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/GetEvent"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Accept Request Object",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.OutPutOfInvite"
                        }
                    }
                }
            }
        },
        "/user/v1/invite": {
            "post": {
                "description": "This endpoint gives info of the sending the invitation.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Send Invite."
                ],
                "summary": "Send Invite Api.",
                "parameters": [
                    {
                        "description": "Accept Request Object",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AcceptRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.OutPutOfInvite"
                        }
                    }
                }
            }
        },
        "/user/v1/login": {
            "post": {
                "description": "This endpoint gives API Authentication makes a user's account more secure by adding that additional layer of authentication which asked user to enter there user name and password and check if those are valid or not.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Login."
                ],
                "summary": "UserLogin",
                "parameters": [
                    {
                        "description": "Accept Request Object",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.userLogin"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Accept Request Object",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.OutPutOfInvite"
                        }
                    }
                }
            }
        },
        "/user/v1/signup": {
            "post": {
                "description": "This API is used to create a new User and a User Registration in a single request.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SignUp."
                ],
                "summary": "SignUp Api.",
                "parameters": [
                    {
                        "description": "Accept Request Object",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UserSignUp"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.OutPutOfInvite"
                        }
                    }
                }
            }
        },
        "/user/v1/token": {
            "post": {
                "description": "This endpoint gives an access token for use with the API.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Get Token."
                ],
                "summary": "Get Token.",
                "parameters": [
                    {
                        "description": "Accept Request Object",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/UsetToken"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Token"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "GetEvent": {
            "type": "object",
            "properties": {
                "host": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "location": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "SlotAccept": {
            "type": "object",
            "properties": {
                "eventAccept": {
                    "type": "integer"
                }
            }
        },
        "Token": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "UsetToken": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "models.AcceptRequest": {
            "type": "object",
            "required": [
                "event_id",
                "user_id"
            ],
            "properties": {
                "event_id": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "models.OutPutOfInvite": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "models.UserSignUp": {
            "type": "object",
            "properties": {
                "fullname": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "models.userLogin": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
